name: "Megan Wallace"
description: "The Personal Homepage for Megan Wallace"

url: "http://megan-a-wallace.co.uk"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
